'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DoAnNMCNPM.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _68186721_metro_wallpapers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("68186721-metro-wallpapers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BOOKMANHINHCHINH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BOOKMANHINHCHINH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BOOKS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BOOKS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonban() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonban", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonhienthi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonhienthi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonhienthi1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonhienthi1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhdangnhapnew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhdangnhapnew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhdangnhapnew1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhdangnhapnew1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhdangnhapnew2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhdangnhapnew2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhlapbaocaocongno() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhlapbaocaocongno", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhlapcaoton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhlapcaoton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhlaphoadonbansach() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhlaphoadonbansach", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhlaphoadonbansachleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhlaphoadonbansachleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhlapphieunhapsachleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhlapphieunhapsachleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhlapphieunhapsachright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhlapphieunhapsachright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhlapphieunhapsachright1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhlapphieunhapsachright1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhlapphieuthutien() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhlapphieuthutien", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhlapphieuthutienTohon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhlapphieuthutienTohon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhnhonew1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhnhonew1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhthaydoiquidinh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhthaydoiquidinh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhtracuusach() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhtracuusach", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonmanhinhtracuusachtohon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonmanhinhtracuusachtohon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BUTTONNEW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUTTONNEW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BUTTONNEW1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUTTONNEW1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BUTTONNEW2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUTTONNEW2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BUTTONNEW3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BUTTONNEW3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonsuasach() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonsuasach", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonthem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonthem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonthemxoa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonthemxoa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CREATENEW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CREATENEW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GiaoDien2ManHinhLapBaoCAo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GiaoDien2ManHinhLapBaoCAo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GIAODIEN2MANHINHLAPBAOCAONEW1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GIAODIEN2MANHINHLAPBAOCAONEW1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GIAODIEN2MANHINHLAPBAOCAONEW2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GIAODIEN2MANHINHLAPBAOCAONEW2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GiaoDienCacManHinhNo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GiaoDienCacManHinhNo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GiaoDienChung() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GiaoDienChung", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GIAODIENDOC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GIAODIENDOC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GIAODIENLAPPHIEUTHUTIEN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GIAODIENLAPPHIEUTHUTIEN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GIAODIENLAPPHIEUTHUTIENNEW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GIAODIENLAPPHIEUTHUTIENNEW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GIAODIENLAPPHIEUTHUTIENNEW1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GIAODIENLAPPHIEUTHUTIENNEW1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GIAODIENMANHINHCHINH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GIAODIENMANHINHCHINH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GiaoDienManHinhDangNhap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GiaoDienManHinhDangNhap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GIAODIENTRACUUSACH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GIAODIENTRACUUSACH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HINHNENHYDRA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HINHNENHYDRA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HINHNENHYDRANEW1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HINHNENHYDRANEW1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HINHNENHYDRANEW2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HINHNENHYDRANEW2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HINHNENHYDRANEW3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HINHNENHYDRANEW3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HINHNENHYDRANEW4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HINHNENHYDRANEW4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HoaDonBanSachManHinhChinh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HoaDonBanSachManHinhChinh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LapBaoCaoCongNo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LapBaoCaoCongNo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LapBaoCaoCongNoManHinhChinh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LapBaoCaoCongNoManHinhChinh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LapBaoCaoTonManHinhChinh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LapBaoCaoTonManHinhChinh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MANHINHCHUCNANGNEW1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MANHINHCHUCNANGNEW1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhlapbaocaocongno() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhlapbaocaocongno", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhlapbaocaoton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhlapbaocaoton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhlaphoadonbansachleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhlaphoadonbansachleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhlaphoadonbansachleft1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhlaphoadonbansachleft1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhlaphoadonbansachRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhlaphoadonbansachRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhlaphoadonbansachRight1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhlaphoadonbansachRight1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhlapphieunhapsachleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhlapphieunhapsachleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhlapphieunhapsachright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhlapphieunhapsachright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhlapphieuthutien() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhlapphieuthutien", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhlapphieuthutien1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhlapphieuthutien1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhlapphieuthutien2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhlapphieuthutien2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ManHinhNhoNew1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ManHinhNhoNew1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhthaydoiquydinh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhthaydoiquydinh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhthaydoiquydinh2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhthaydoiquydinh2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhthaydoiquydinh3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhthaydoiquydinh3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhthaydoiquydinh4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhthaydoiquydinh4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property manhinhtracuusach() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manhinhtracuusach", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MAYIN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MAYIN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MAYIn2HAIMANHINHBAOCAO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MAYIn2HAIMANHINHBAOCAO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MayTinh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MayTinh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MENU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MENU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MINIMIZE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MINIMIZE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PEOPLES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PEOPLES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SEARCH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SEARCH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SEARCHManHinhChinh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SEARCHManHinhChinh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Setting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Setting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SHUTDOWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SHUTDOWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TIENMANHINHCHINH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TIENMANHINHCHINH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TUITIEN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TUITIEN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UITHINHNEN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UITHINHNEN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UITHINHNENNEW2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UITHINHNENNEW2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UPDATE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UPDATE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x-icon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
